name: deploy to aliyun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 47-self
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: npm install and build
        run: |
            npm install
            npm run build
        env:
            CI: true
      - name: deploy
        run: pm2 restart my-blog